### ISSUE TITLE
Result type is of type type_type instead of type

### ISSUE THREAD

**Issue by wilkovanderveen** [kfinley/TypeMerger#5]
I am trying to merge two objects of the same type and I was expecting an object of that type. Instead I retrieved an object of type type_type.

I am using version 2.1 on .NET standard 2.0 with .NET core 3.1

**Comment by kfinley** [comment]
You are indeed correct. As the project states:

> It allows two objects of any type to be merged into a **_new `Type`._**

If you are working with 2 objects of the same type and your goal is to map property values of one object to the other object then I would recommend you look at [AutoMapper](https://automapper.org) because it's the framework that does what you're trying to do.

TypeMerger was never intended to map objects and its only job is to create new types from two types.
